server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://mysql-0.mysql:3306/gitops
    username: root
    password: zaid@11
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

